version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: kumarank156/easy-chat
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    